const DEFAULT_PROGRAMS = [
  {name:'Full Body A',notes:'FULL BODY A – følg oppgitt tempo og RIR.',exercises:[
    ['Dype knebøy',3,'10–12','3–1–1–0',120,'RIR 1–2'],['Benkpress',3,'6–8','3–0–1–0',120,'RIR 1–2'],['Pull-ups',3,'6–10','2–1–1–1',120,'RIR 1–2'],['RDL',3,'8–10','3–1–1–0',120,'RIR 1–2'],['Sidehev',3,'12–20','2–0–1–1',120,'RIR 0–1'],['EZ-bar curl',3,'10–15','3–0–1–1',120,'RIR 0–1'],['Triceps pushdown',3,'10–15','2–0–1–1',120,'RIR 0–1'],['Cable crunch',3,'8–12','3–1–1–1',120,'RIR 0–1']
  ]},
  {name:'Full Body B',notes:'FULL BODY B – følg oppgitt tempo og RIR.',exercises:[
    ['RDL',3,'10–12','3–1–1–0',120,'RIR 1–2'],['Incline DB press',3,'8–12','3–0–1–0',120,'RIR 1–2'],['Chest-supp. row',3,'8–12','3–1–1–1',120,'RIR 1–2'],['Bulgarian squat',3,'8–12','3–1–1–0',120,'RIR 1–2'],['DB shoulder press',3,'8–12','3–0–1–0',120,'RIR 1–2'],['Leg extension',3,'12–15','3–0–1–1',120,'RIR 0–1'],['Leg curl',3,'10–15','3–1–1–1',120,'RIR 0–1'],['Hanging leg raise',3,'8–12','3–1–2–1',120,'RIR 0–1']
  ]},
  {name:'Dag C – revidert',notes:'Supersett A–D. Følg oppgitt tempo og RIR.',exercises:[
    ['A1 · Utfall fra boks',3,'8–12','3–1–1–0',120,'RIR 1–2 · Supersett med A2'],['A2 · Chin-ups',3,'6–10','2–1–1–1',120,'RIR 1–2 · Supersett med A1'],['B1 · Dype Smith-knebøy',3,'12–15','3–1–1–0',120,'RIR 1–2 · Supersett med B2'],['B2 · Weighted dips',3,'6–10','3–1–1–0',120,'RIR 1–2 · Supersett med B1'],['C1 · Sidehev',2,'10–15','2–0–1–1',120,'RIR 0–1 · Supersett med C2'],['C2 · Cable flyes',2,'8–12','3–1–1–1',120,'RIR 0–1 · Supersett med C1'],['D1 · Cable hammer curl',2,'10–15','3–0–1–1',120,'RIR 0–1 · Supersett med D2'],['D2 · Ab wheel rollout',3,'6–12','3–1–1–0',120,'RIR 0–1 · Supersett med D1']
  ]},
  {name:'Calisthenics / CrossFit ekstraøkt',notes:'Trekk, dips, skuldre og progresjon mot HSPU og stående ab-wheel rollout.',exercises:[
    ['Pull-ups / chins / neutral grip pull-ups',4,'5–8','3–1–X–1',150,'Bytt grep mellom økter.'],['Liggende roing / horizontal pull-ups',4,'8–12','3–1–1–1',120,'Stram kropp og skulderbladskontroll.'],['Dype dips',4,'6–10','3–1–1–0',150,'Bruk smertefri dybde.'],['Pike push-ups / HSPU-progresjon',4,'4–8','3–1–X–1',150,'Øk gradvis høyden på føttene.'],['Scapular wall slides / skulderkontroll',3,'10–15','rolig',60,'Kontrollert bevegelse.'],['Ab wheel – knestående til lang rekkevidde',4,'5–10','3–1–2–0',120,'Progresjon mot stående rollout.'],['Stående ab-wheel negativ',3,'2–5','5 sek ut',150,'Bruk vegg/stoppunkt ved behov.']
  ]}
].map((p,pi)=>({id:'p'+pi,name:p.name,notes:p.notes,exercises:p.exercises.map((e,ei)=>({id:`p${pi}e${ei}`,name:e[0],targetSets:e[1],targetReps:e[2],tempo:e[3],restSeconds:e[4],notes:e[5]}))}));

const KEY='treningslogg-pwa-v1';
let state=loadState();
let timerHandle=null;

function loadState(){
  try{
    const raw=localStorage.getItem(KEY); if(raw){const s=JSON.parse(raw); return {...s,programs:s.programs?.length?s.programs:structuredClone(DEFAULT_PROGRAMS),sessions:s.sessions||[],active:s.active||null,timer:s.timer||null};}
  }catch(e){}
  return {programs:structuredClone(DEFAULT_PROGRAMS),sessions:[],active:null,timer:null};
}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state));}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmtDate(iso){return new Intl.DateTimeFormat('nb-NO',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));}
function normalizedName(n){return n.replace(/^[A-D][12]\s*[·.-]?\s*/i,'').trim().toLowerCase();}
function repRange(t){const n=(t.match(/\d+/g)||[]).map(Number); return n.length?[Math.min(...n),Math.max(...n)]:null;}
function rirRange(t){const m=(t.match(/RIR\s*(\d+)(?:[–-](\d+))?/i)||[]); if(!m.length)return null; const a=+m[1],b=m[2]?+m[2]:a; return [Math.min(a,b),Math.max(a,b)];}
function volume(s){return s.exercises.flatMap(e=>e.sets).reduce((a,x)=>a+(Number(x.weight)||0)*(Number(x.reps)||0),0)}
function oneRM(w,r){return w>0&&r>0?w*(1+r/30):0}
function smallExercise(n){return ['sidehev','curl','pushdown','fly','leg extension','leg curl'].some(k=>normalizedName(n).includes(k));}
function round05(v){return Math.round(v*2)/2}
function fmtW(v){return Number.isInteger(v)?String(v):v.toFixed(1).replace('.',',')}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function setTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));renderAll();}

function startWorkout(programId){const p=state.programs.find(x=>x.id===programId); if(!p)return; if(state.active && !confirm('Du har allerede en pågående økt. Erstatt den?'))return; state.active={id:uid(),programID:p.id,name:p.name,startedAt:new Date().toISOString(),notes:'',exercises:p.exercises.map(e=>({id:uid(),sourceExerciseID:e.id,name:e.name,targetReps:e.targetReps,tempo:e.tempo,restSeconds:e.restSeconds,notes:e.notes,sets:Array.from({length:e.targetSets},()=>({id:uid(),weight:'',reps:'',rir:'',completed:false}))}))}; saveState(); setTab('workout');}
function addSet(eid){const e=state.active?.exercises.find(x=>x.id===eid);if(!e)return;e.sets.push({id:uid(),weight:'',reps:'',rir:'',completed:false});saveState();renderWorkout();}
function removeExercise(eid){if(!state.active)return;state.active.exercises=state.active.exercises.filter(e=>e.id!==eid);saveState();renderWorkout();}
function updateSet(eid,sid,key,value){const e=state.active?.exercises.find(x=>x.id===eid);const s=e?.sets.find(x=>x.id===sid);if(!s)return;s[key]=value;saveState();updateWorkoutSummary();}
function toggleSet(eid,sid){const e=state.active?.exercises.find(x=>x.id===eid);const s=e?.sets.find(x=>x.id===sid);if(!s)return;s.completed=!s.completed;if(s.completed)startTimer(e.restSeconds);saveState();renderWorkout();}
function startTimer(sec){state.timer={end:Date.now()+sec*1000,duration:sec};saveState();tickTimer();if(timerHandle)clearInterval(timerHandle);timerHandle=setInterval(tickTimer,1000)}
function stopTimer(){state.timer=null;saveState();if(timerHandle)clearInterval(timerHandle);timerHandle=null;renderWorkout();}
function tickTimer(){if(!state.timer)return;const left=Math.max(0,Math.ceil((state.timer.end-Date.now())/1000));const el=document.querySelector('#timerValue');if(el)el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0){stopTimer();toast('Pause ferdig');}}
function mostRecentExercise(name){const key=normalizedName(name);for(const sess of state.sessions){const e=sess.exercises.find(x=>normalizedName(x.name)===key);if(e)return e}return null}
function progressionSuggestion(e){const rr=repRange(e.targetReps),prev=mostRecentExercise(e.name);if(!rr||!prev)return null;const sets=prev.sets.filter(s=>(s.completed||s.reps)&&Number(s.reps)>0);if(!sets.length)return null;const reps=sets.map(s=>Number(s.reps));const maxRep=Math.max(...reps);const avgRir=sets.filter(s=>s.rir!==''&&s.rir!=null).reduce((a,s,_,arr)=>a+Number(s.rir)/arr.length,0);const target=rirRange(e.notes);const weightVals=sets.map(s=>Number(s.weight)).filter(w=>w>0);const w=weightVals.length?Math.max(...weightVals):null;
  if(target && Number.isFinite(avgRir) && avgRir<target[0]) return {title:'Hold igjen litt',detail:`Sist lå du rundt RIR ${avgRir.toFixed(1).replace('.',',')}, under målet ${target[0]}–${target[1]}. Behold eller reduser belastningen litt.`};
  if(maxRep>=rr[1]){if(w){const next=round05(w+(smallExercise(e.name)?1:2.5));return{title:'Øk belastningen',detail:`Du traff toppen av rep-rangen sist. Prøv ca. ${fmtW(next)} kg og bygg opp fra ${rr[0]} reps.`}}return{title:'Gjør varianten tyngre',detail:`Du traff toppen av rep-rangen sist. Øk vanskelighetsgrad eller ekstern belastning og start rundt ${rr[0]} reps.`}}
  if(maxRep>=rr[0])return{title:'Bygg flere reps',detail:`Behold omtrent samme belastning/variant og prøv ${Math.min(rr[1],maxRep+1)} reps på minst ett sett.`};
  return{title:'Bygg inn i målområdet',detail:`Sikt på minst ${rr[0]} kontrollerte reps før du øker belastningen.`};
}
function isPR(name,w,r){const cand=oneRM(Number(w),Number(r));if(!cand)return false;let best=0;for(const sess of state.sessions)for(const e of sess.exercises)if(normalizedName(e.name)===normalizedName(name))for(const s of e.sets)best=Math.max(best,oneRM(Number(s.weight),Number(s.reps)));return cand>best;}

function renderPrograms(){
  const el=document.querySelector('#programs');
  const cards=state.programs.map(p=>`<div class="card"><div class="row wrap"><div><h3>${esc(p.name)}</h3><div class="muted small">${p.exercises.length} øvelser</div></div><button class="primary" data-start="${p.id}">Start økt</button></div><p class="muted small">${esc(p.notes)}</p>${p.exercises.map(e=>`<div class="exercise"><div class="exercise-title">${esc(e.name)}</div><div class="meta">${e.targetSets} × ${esc(e.targetReps)} · Tempo ${esc(e.tempo)} · ${esc(e.notes)} · Pause ${e.restSeconds}s</div></div>`).join('')}</div>`).join('');
  el.innerHTML=`<div class="card"><h2>Treningsprogram</h2><p class="muted small">Start en ferdig økt eller se detaljene. Du kan legge til ekstra øvelser etter at økten er startet.</p></div>`+cards;
  el.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>startWorkout(b.dataset.start)));
}

function renderWorkout(){const el=document.querySelector('#workout');if(!state.active){el.innerHTML=`<div class="card empty"><h2>Ingen aktiv økt</h2><p>Velg et program og trykk «Start økt».</p><button class="primary" id="goPrograms">Velg program</button></div>`;el.querySelector('#goPrograms').onclick=()=>setTab('programs');return;}
  const a=state.active; const timer=state.timer?`<div class="timer"><div><div class="small">Hviletimer</div><strong id="timerValue">—</strong></div><button class="ghost" id="stopTimer">Stopp</button></div>`:'';
  el.innerHTML=`${timer}<div class="card"><div class="row wrap"><div><h2>${esc(a.name)}</h2><div class="muted small">Startet ${fmtDate(a.startedAt)}</div></div><div class="right"><div class="muted small">Volum</div><div class="volume" id="workoutVolume">${Math.round(volume(a)).toLocaleString('nb-NO')} kg</div></div></div></div>`+
  a.exercises.map(e=>{const sug=progressionSuggestion(e);return`<div class="card"><div class="row wrap"><div><h3>${esc(e.name)}</h3><div class="meta">${esc(e.targetReps)} reps · Tempo ${esc(e.tempo)} · ${esc(e.notes)} · ${e.restSeconds}s</div></div><button class="ghost small" data-remove="${e.id}">Fjern</button></div>${sug?`<div class="suggestion"><strong>${esc(sug.title)}</strong><br>${esc(sug.detail)}</div>`:''}<div class="set-head"><span>#</span><span>kg</span><span>reps</span><span>RIR</span><span>✓</span></div>${e.sets.map((s,i)=>`<div class="set-row"><span class="muted small">${i+1}</span><input inputmode="decimal" type="number" min="0" step="0.5" value="${esc(s.weight)}" data-e="${e.id}" data-s="${s.id}" data-k="weight"><input inputmode="numeric" type="number" min="0" step="1" value="${esc(s.reps)}" data-e="${e.id}" data-s="${s.id}" data-k="reps"><input inputmode="decimal" type="number" min="0" max="10" step="0.5" value="${esc(s.rir)}" data-e="${e.id}" data-s="${s.id}" data-k="rir"><button class="check ${s.completed?'done':''}" data-check-e="${e.id}" data-check-s="${s.id}">${s.completed?'✓':'○'}</button></div>${isPR(e.name,s.weight,s.reps)&&s.weight&&s.reps?`<div class="pr">Potensiell PR</div>`:''}`).join('')}<button class="ghost small" data-addset="${e.id}">+ Sett</button></div>`}).join('')+
  `<div class="card"><button class="ghost" id="addExercise">+ Legg til ekstra øvelse</button><div class="divider"></div><label>Notater<textarea id="workoutNotes" rows="3" placeholder="Form, teknikk, dagsform…">${esc(a.notes||'')}</textarea></label><div class="grid2" style="margin-top:12px"><button class="danger" id="cancelWorkout">Avbryt</button><button class="primary" id="finishWorkout">Fullfør og lagre</button></div></div>`;
  el.querySelectorAll('input[data-k]').forEach(i=>i.addEventListener('input',()=>updateSet(i.dataset.e,i.dataset.s,i.dataset.k,i.value)));
  el.querySelectorAll('[data-check-e]').forEach(b=>b.onclick=()=>toggleSet(b.dataset.checkE,b.dataset.checkS));
  el.querySelectorAll('[data-addset]').forEach(b=>b.onclick=()=>addSet(b.dataset.addset));
  el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Fjerne denne øvelsen fra dagens økt?'))removeExercise(b.dataset.remove)});
  el.querySelector('#addExercise').onclick=openAddExercise;
  el.querySelector('#workoutNotes').oninput=e=>{state.active.notes=e.target.value;saveState()};
  el.querySelector('#cancelWorkout').onclick=()=>{if(confirm('Avbryte økten? Registreringene i denne økten slettes.')){state.active=null;stopTimer();saveState();renderAll()}};
  el.querySelector('#finishWorkout').onclick=finishWorkout;
  if(state.timer){el.querySelector('#stopTimer').onclick=stopTimer;tickTimer();if(!timerHandle)timerHandle=setInterval(tickTimer,1000)}
}
function updateWorkoutSummary(){const el=document.querySelector('#workoutVolume');if(el&&state.active)el.textContent=`${Math.round(volume(state.active)).toLocaleString('nb-NO')} kg`;}
function openAddExercise(){const m=document.querySelector('#modal'),b=document.querySelector('#modalBody');b.innerHTML=`<h3>Ekstra øvelse</h3><div class="stack"><label>Navn<input id="xName" placeholder="F.eks. Face pull" required></label><div class="grid2"><label>Sett<input id="xSets" type="number" min="1" max="12" value="3"></label><label>Reps<input id="xReps" value="8–12"></label></div><div class="grid2"><label>Tempo<input id="xTempo" value="3–1–1–0"></label><label>Pause (sek)<input id="xRest" type="number" min="0" value="120"></label></div><label>Mål / RIR<input id="xNotes" value="RIR 1–2"></label><div class="grid2"><button value="cancel" class="ghost">Avbryt</button><button type="button" class="primary" id="saveExtra">Legg til</button></div></div>`;m.showModal();b.querySelector('#saveExtra').onclick=()=>{const name=b.querySelector('#xName').value.trim();if(!name)return toast('Skriv navn på øvelsen');const n=Math.max(1,Math.min(12,+b.querySelector('#xSets').value||3));state.active.exercises.push({id:uid(),name,targetReps:b.querySelector('#xReps').value.trim(),tempo:b.querySelector('#xTempo').value.trim(),restSeconds:Math.max(0,+b.querySelector('#xRest').value||0),notes:b.querySelector('#xNotes').value.trim(),sets:Array.from({length:n},()=>({id:uid(),weight:'',reps:'',rir:'',completed:false}))});saveState();m.close();renderWorkout()};}
function finishWorkout(){if(!state.active)return;const any=state.active.exercises.some(e=>e.sets.some(s=>s.completed||Number(s.reps)>0));if(!any)return toast('Registrer minst ett sett først');const done=structuredClone(state.active);done.finishedAt=new Date().toISOString();state.sessions.unshift(done);state.active=null;stopTimer();saveState();toast('Økten er lagret');setTab('history');}

function renderHistory(){const el=document.querySelector('#history');if(!state.sessions.length){el.innerHTML=`<div class="card empty"><h2>Ingen historikk ennå</h2><p>Fullfør en økt, så vises den her.</p></div>`;return;}el.innerHTML=`<div class="card"><h2>Historikk</h2><p class="muted small">${state.sessions.length} lagrede økter</p></div>`+state.sessions.map((s,si)=>`<div class="card"><div class="row wrap"><div><h3>${esc(s.name)}</h3><div class="muted small">${fmtDate(s.finishedAt||s.startedAt)}</div></div><div class="right"><div class="muted small">Volum</div><strong>${Math.round(volume(s)).toLocaleString('nb-NO')} kg</strong></div></div>${s.exercises.map(e=>`<div class="exercise"><div class="exercise-title">${esc(e.name)}</div>${e.sets.filter(x=>x.completed||x.reps).map((x,i)=>`<div class="history-set">Sett ${i+1}: ${x.weight||0} kg × ${x.reps||0}${x.rir!==''&&x.rir!=null?` · RIR ${x.rir}`:''}</div>`).join('')}</div>`).join('')}${s.notes?`<p class="muted small">${esc(s.notes)}</p>`:''}<button class="danger small" data-del-session="${si}">Slett økt</button></div>`).join('');el.querySelectorAll('[data-del-session]').forEach(b=>b.onclick=()=>{if(confirm('Slette denne økten permanent?')){state.sessions.splice(+b.dataset.delSession,1);saveState();renderHistory();renderProgress()}})}

function personalRecords(){const best=new Map();for(const s of state.sessions)for(const e of s.exercises)for(const set of e.sets){const v=oneRM(+set.weight,+set.reps);if(!v)continue;const key=normalizedName(e.name),cur=best.get(key);if(!cur||v>cur.e1rm)best.set(key,{name:e.name,weight:+set.weight,reps:+set.reps,e1rm:v,date:s.finishedAt||s.startedAt})}return [...best.values()].sort((a,b)=>a.name.localeCompare(b.name,'nb'));}
function seriesFor(name){const key=normalizedName(name),arr=[];for(const s of [...state.sessions].reverse()){const e=s.exercises.find(x=>normalizedName(x.name)===key);if(!e)continue;let best=0;for(const set of e.sets)best=Math.max(best,oneRM(+set.weight,+set.reps));if(best)arr.push({date:s.finishedAt||s.startedAt,value:best})}return arr;}
function svgChart(data){if(data.length<2)return`<div class="muted small">Trenger minst to registrerte økter for graf.</div>`;const w=600,h=170,p=24,min=Math.min(...data.map(d=>d.value)),max=Math.max(...data.map(d=>d.value)),span=Math.max(1,max-min);const pts=data.map((d,i)=>`${p+i*(w-2*p)/(data.length-1)},${h-p-(d.value-min)*(h-2*p)/span}`).join(' ');return`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Progresjonsgraf"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="currentColor" opacity=".2"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${data.map((d,i)=>{const [x,y]=pts.split(' ').map(p=>p.split(','))[i];return`<circle cx="${x}" cy="${y}" r="5" fill="currentColor"><title>${d.value.toFixed(1)} kg e1RM</title></circle>`}).join('')}</svg><div class="row small muted"><span>${data[0].value.toFixed(1)} kg</span><span>${data.at(-1).value.toFixed(1)} kg e1RM</span></div>`}
function renderProgress(){const el=document.querySelector('#progress'),prs=personalRecords();if(!prs.length){el.innerHTML=`<div class="card empty"><h2>Ingen progresjonsdata ennå</h2><p>Logg økter med vekt og reps for å få PR-er og grafer.</p></div>`;return;}const names=[...new Set(prs.map(p=>p.name))];const selected=el.dataset.selected||names[0];if(!names.includes(selected))el.dataset.selected=names[0];const actual=el.dataset.selected||names[0];el.innerHTML=`<div class="card"><h2>Progresjon</h2><label>Øvelse<select id="progressExercise">${names.map(n=>`<option ${n===actual?'selected':''}>${esc(n)}</option>`).join('')}</select></label><div style="margin-top:12px">${svgChart(seriesFor(actual))}</div></div><div class="card"><h3>Personlige rekorder</h3>${prs.map(p=>`<div class="exercise"><div class="row"><div><strong>${esc(p.name)}</strong><div class="muted small">${fmtDate(p.date)}</div></div><div class="right"><strong>${fmtW(p.weight)} kg × ${p.reps}</strong><div class="muted small">e1RM ${p.e1rm.toFixed(1).replace('.',',')} kg</div></div></div></div>`).join('')}</div>`;el.querySelector('#progressExercise').onchange=e=>{el.dataset.selected=e.target.value;renderProgress()};}

function renderSettings(){const el=document.querySelector('#settings');el.innerHTML=`<div class="card"><h2>Backup og data</h2><p class="muted small">Alt lagres lokalt på denne iPhonen. Eksporter en backup med jevne mellomrom.</p><div class="stack"><button class="primary" id="exportBtn">Eksporter backup</button><label class="file-label">Importer backup<input type="file" id="importFile" accept="application/json,.json"></label></div></div><div class="card"><h3>Programmaler</h3><p class="muted small">Tilbakestilling gjenoppretter A, B, C og calisthenics-malen. Historikken slettes ikke.</p><button class="ghost" id="resetPrograms">Tilbakestill programmaler</button></div><div class="card"><h3>Om hybrid-versjonen</h3><p class="muted small">Installeres fra Safari på Hjem-skjermen, fungerer offline etter første lasting, og krever ikke Xcode.</p></div>`;el.querySelector('#exportBtn').onclick=exportData;el.querySelector('#importFile').onchange=importData;el.querySelector('#resetPrograms').onclick=()=>{if(confirm('Tilbakestille programmalene?')){state.programs=structuredClone(DEFAULT_PROGRAMS);saveState();renderAll();toast('Programmalene er gjenopprettet')}};}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),format:'treningslogg-pwa-v1'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`treningslogg-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importData(ev){const f=ev.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);if(!Array.isArray(s.sessions)||!Array.isArray(s.programs))throw new Error();if(!confirm('Importer backup og erstatt dataene i appen?'))return;state={programs:s.programs,sessions:s.sessions,active:s.active||null,timer:null};saveState();renderAll();toast('Backup importert')}catch(e){alert('Kunne ikke lese backup-filen.')}};r.readAsText(f);}

function renderAll(){renderPrograms();renderWorkout();renderHistory();renderProgress();renderSettings();document.querySelector('#statusLine').textContent=state.active?`Pågående: ${state.active.name}`:`${state.sessions.length} lagrede økter`;}
function installHelp(){const m=document.querySelector('#modal'),b=document.querySelector('#modalBody');b.innerHTML=`<h3>Installer på iPhone</h3><ol class="install-steps"><li>Åpne denne appen i <strong>Safari</strong>.</li><li>Trykk <strong>Del</strong>-knappen.</li><li>Velg <strong>Legg til på Hjem-skjerm</strong>.</li><li>Trykk <strong>Legg til</strong>.</li></ol><p class="muted small">Appen åpnes deretter i eget vindu og fungerer offline etter første lasting.</p><button value="cancel" class="primary" style="width:100%">Lukk</button>`;m.showModal();}

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
document.querySelector('#installHelpBtn').addEventListener('click',installHelp);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderAll();
if(state.timer){tickTimer();timerHandle=setInterval(tickTimer,1000)}
